spring:
  application:
    name: driver-license

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/uju}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:superscret}

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
      database: ${SPRING_REDIS_DATABASE:0}
      timeout: ${SPRING_REDIS_TIMEOUT:2000}

ark:
  driver-license:
    type: ${ARK_DRIVER_LICENSE_TYPE:redis}
